sudo: required #is required to use docker service in travis

language: php #can be any language, just php for example

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

jobs:
  include:
    - os: linux
      arch: amd64
    - os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge

services:
  - docker

install:
  - echo "install nothing!"

before_script:
  - docker --version
  - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
  - env

script:
  - docker build -t ${DOCKER_USERNAME}/release:test-${TRAVIS_ARCH} .
  - docker push ${DOCKER_USERNAME}/release:test-${TRAVIS_ARCH}

after_success:
  - docker manifest create ${DOCKER_USERNAME}/release:test --amend ${DOCKER_USERNAME}/release:test-amd64 --amend ${DOCKER_USERNAME}/release:test-aarch64
  - docker manifest push ${DOCKER_USERNAME}/release:test
