sudo: required #is required to use docker service in travis

language: php #can be any language, just php for example

arch:
  - amd64
  - arm64-graviton2

services:
  - docker # required, but travis uses older version of docker :(

install:
  - echo "install nothing!" # put your normal pre-testing installs here

before_script:
  - docker --version
  - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
  - env

script:
  - docker build -t ${DOCKER_USERNAME}/release:test-${TRAVIS_ARCH} .
  - docker push ${DOCKER_USERNAME}/release:test-${TRAVIS_ARCH}

after_success:
  - docker manifest create ${DOCKER_USERNAME}/release:test --amend ${DOCKER_USERNAME}/release:test-amd64 --amend ${DOCKER_USERNAME}/release:test-arm64 
  - docker manifest push ${DOCKER_USERNAME}/release:test-latest
