sudo: required #is required to use docker service in travis

language: minimal

services:
  - docker

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

stages:
  - build
  - publish

install: skip

jobs:
  include:
    - stage: build
      script: ./build.sh
      os: linux
      arch: amd64
    - stage: build
      script: ./build.sh
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
    - stage: compile
      script: ./publish.sh

before_script:
  - docker --version
  - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
